In [2]:
import pandas as pd

In [30]:
data = pd.read_csv("./Data_cleaned/Pop_BE_Changement_population_clean.csv", sep=";", )
data = data[data["Année de référence"] == "1992-01-01"]

In [31]:
data

,CODE INS,LIEU DE RESIDENCE,Année de référence,Région,Province,POPULATION ANNEE DE REFERENCE,NAISSANCES,DECES,ENTREES_INTERNES,SORTIES_INTERNES,IMMIGRATIONS,CHANGEMENTS REGISTRE (ENTREES),REINSCRITS AYANT ETE RAYES,EMIGRATIONS,CHANGEMENTS REGISTRE (SORTIES),RAYES D'OFFICE,AJUSTEMENT STATISTIQUE,NATIONALITE BELGE EN NON-BELGE,NATIONALITE NON-BELGE EN BELGE,POPULATION DE L'ANNEE SUIVANTE
0,11001,Aartselaar,1992-01-01,Flandre,Anvers,14309,189,148,735,670,37,NaN,4,17,NaN,1,-1,1,9,14437
1,11002,Anvers,1992-01-01,Flandre,Anvers,465783,6061,5702,11213,15208,5939,NaN,1399,1776,NaN,2574,-33,30,1980,465102
2,11004,Boechout,1992-01-01,Flandre,Anvers,11309,141,112,620,590,30,NaN,3,11,NaN,4,-4,1,12,11382
3,11005,Boom,1992-01-01,Flandre,Anvers,13937,141,233,642,603,31,NaN,12,12,NaN,12,0,0,36,13903
4,11007,Borsbeek,1992-01-01,Flandre,Anvers,10074,190,81,781,741,37,NaN,8,18,NaN,12,-2,0,15,10236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,93018,Doische,1992-01-01,Wallonie,Namur,2804,34,38,154,115,12,NaN,5,6,NaN,1,-3,0,2,2846
585,93022,Florennes,1992-01-01,Wallonie,Namur,10619,135,123,521,453,36,NaN,13,23,NaN,2,1,0,21,10724
586,93056,Philippeville,1992-01-01,Wallonie,Namur,7317,100,83,424,374,10,NaN,11,13,NaN,6,-2,0,10,7384
587,93088,Walcourt,1992-01-01,Wallonie,Namur,15897,193,177,836,620,42,NaN,11,48,NaN,13,0,1,53,16121
588,93090,Viroinval,1992-01-01,Wallonie,Namur,5560,64,63,276,250,31,NaN,5,5,NaN,6,-1,0,13,5611

In [33]:
def INS_to_arrondissement (dataframe, INS_col, arrondissement_col):
    """
    Converts the column containing INS codes into the corresponding arrondissement, then adds arrondissement to the DataFrame.

        • dataframe: pandas.DataFrame item to which to add the column.
        • INS_col: str, name of column in your pandas.DataFrame containing the INS codes.
        • arrondissement_col: str, name to give to the new column that will contain arrondissements.
    """
    
    dataframe[arrondissement_col] = ""
    dataframe[INS_col] = dataframe[INS_col].astype(int)
    
    for INS in dataframe[INS_col]:
        if INS > 93000:
            dataframe[arrondissement_col] = "Philippeville"
        
        if INS > 92000:
            dataframe[arrondissement_col] = "Namur"
        
        if INS > 91000:
            dataframe[arrondissement_col] = "Dinant"
        
        if INS > 85000:
            dataframe[arrondissement_col] = "Virton"
        
        if INS > 84000:
            dataframe[arrondissement_col] = "Neufchâteau"
        
        if INS > 83000:
            dataframe[arrondissement_col] = "Marche-en-Famenne"
        
        if INS > 82000:
            dataframe[arrondissement_col] = "Bastogne"
        
        if INS > 81000:
            dataframe[arrondissement_col] = "Arlon" 
        
        if INS > 73000:
            dataframe[arrondissement_col] = "Tongres"
        
        if INS > 72000:
            dataframe[arrondissement_col] = "Maaseik"

        if INS > 71000:
            dataframe[arrondissement_col] = "Hasselt"

        if INS > 64000:
            dataframe[arrondissement_col] = "Waremme"

        if INS > 63000:
            dataframe[arrondissement_col] = "Verviers"

        if INS > 62000:
            dataframe[arrondissement_col] = "Liège"

        if INS > 61000:
            dataframe[arrondissement_col] = "Huy"

        if INS > 58000:
            dataframe[arrondissement_col] = "La Louvière"
  
        if INS > 57000:
            dataframe[arrondissement_col] = "Tournai"

        if INS > 56000:
            dataframe[arrondissement_col] = "Thuin"

        if INS > 55000:
            dataframe[arrondissement_col] = "Soignies"

        if INS > 54000:
            dataframe[arrondissement_col] = "Mouscron"
  
        if INS > 53000:
            dataframe[arrondissement_col] = "Mons"
   
        if INS > 52000:
            dataframe[arrondissement_col] = "Charleroi"
   
        if INS > 51000:
            dataframe[arrondissement_col] = "Ath"
    
        if INS > 46000:
            dataframe[arrondissement_col] = "Saint-Nicolas"
    
        if INS > 45000:
            dataframe[arrondissement_col] = "Audenarde"
    
        if INS > 44000:
            dataframe[arrondissement_col] = "Gand"
    
        if INS > 43000:
            dataframe[arrondissement_col] = "Eeklo"
    
        if INS > 42000:
            dataframe[arrondissement_col] =  "Termonde"

        if INS > 41000:
            dataframe[arrondissement_col] = "Alost"
 
        if INS > 38000:
            dataframe[arrondissement_col] = "Furnes"
 
        if INS > 37000:
            dataframe[arrondissement_col] = "Tielt"
  
        if INS > 36000:
            dataframe[arrondissement_col] = "Roulers"
 
        if INS > 35000:
            dataframe[arrondissement_col] = "Ostende"
  
        if INS > 34000:
            dataframe[arrondissement_col] = "Courtrai"
   
        if INS > 33000:
            dataframe[arrondissement_col] = "Ypres"
    
        if INS > 32000:
            dataframe[arrondissement_col] = "Dixmude"
    
        if INS > 31000:
            dataframe[arrondissement_col] = "Bruges"
  
        if INS > 25000:
            dataframe[arrondissement_col] = "Nivelles" 
   
        if INS > 24000:
            dataframe[arrondissement_col] = "Louvain"
    
        if INS > 23000:
            dataframe[arrondissement_col] = "Hal-Vilvorde"
    
        if INS > 21000:
            dataframe[arrondissement_col] = "Bruxelles"
    
        if INS > 13000:
            dataframe[arrondissement_col] = "Turnhout"
  
        if INS > 12000:
            dataframe[arrondissement_col] = "Malines"
  
        if INS > 11000:
            dataframe[arrondissement_col] = "Anvers"
        
        else:
            dataframe[arrondissement_col] = "Inconnu"

In [34]:
INS_to_arrondissement(data, "CODE INS", "Arrondissement")

In [35]:
data

,CODE INS,LIEU DE RESIDENCE,Année de référence,Région,Province,POPULATION ANNEE DE REFERENCE,NAISSANCES,DECES,ENTREES_INTERNES,SORTIES_INTERNES,...,CHANGEMENTS REGISTRE (ENTREES),REINSCRITS AYANT ETE RAYES,EMIGRATIONS,CHANGEMENTS REGISTRE (SORTIES),RAYES D'OFFICE,AJUSTEMENT STATISTIQUE,NATIONALITE BELGE EN NON-BELGE,NATIONALITE NON-BELGE EN BELGE,POPULATION DE L'ANNEE SUIVANTE,Arrondissement
0,11001,Aartselaar,1992-01-01,Flandre,Anvers,14309,189,148,735,670,...,NaN,4,17,NaN,1,-1,1,9,14437,Anvers
1,11002,Anvers,1992-01-01,Flandre,Anvers,465783,6061,5702,11213,15208,...,NaN,1399,1776,NaN,2574,-33,30,1980,465102,Anvers
2,11004,Boechout,1992-01-01,Flandre,Anvers,11309,141,112,620,590,...,NaN,3,11,NaN,4,-4,1,12,11382,Anvers
3,11005,Boom,1992-01-01,Flandre,Anvers,13937,141,233,642,603,...,NaN,12,12,NaN,12,0,0,36,13903,Anvers
4,11007,Borsbeek,1992-01-01,Flandre,Anvers,10074,190,81,781,741,...,NaN,8,18,NaN,12,-2,0,15,10236,Anvers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,93018,Doische,1992-01-01,Wallonie,Namur,2804,34,38,154,115,...,NaN,5,6,NaN,1,-3,0,2,2846,Anvers
585,93022,Florennes,1992-01-01,Wallonie,Namur,10619,135,123,521,453,...,NaN,13,23,NaN,2,1,0,21,10724,Anvers
586,93056,Philippeville,1992-01-01,Wallonie,Namur,7317,100,83,424,374,...,NaN,11,13,NaN,6,-2,0,10,7384,Anvers
587,93088,Walcourt,1992-01-01,Wallonie,Namur,15897,193,177,836,620,...,NaN,11,48,NaN,13,0,1,53,16121,Anvers
588,93090,Viroinval,1992-01-01,Wallonie,Namur,5560,64,63,276,250,...,NaN,5,5,NaN,6,-1,0,13,5611,Anvers